apiVersion: v1
kind: Service
metadata:
  name: routr
  labels:
    app: routr
spec:
  type: LoadBalancer
  # "Local" preserves the client source IP and avoids a second hop for
  # LoadBalancer and NodePort
  externalTrafficPolicy: Local
  ports:
  - name: sip
    port: 5060
  - name: https
    port: 4567
  selector:
    app: routr
    tier: sip
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: routr
  labels:
    app: routr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: routr
        tier: sip
    spec:
      containers:
      - name: routr
        image: fonoster/routr:1.0.0-edge-20200606
        env:
        - name: ROUTR_DS_PROVIDER
          value: redis_data_provider
        - name: ROUTR_DS_PARAMETERS
          value: host=redis-routr,port=6379
        ports:
        - containerPort: 5060
          name: sip
        - containerPort: 4567
          name: https
        volumeMounts:
        - name: log4j2
          mountPath: /opt/routr/config/log4j2.yml
          subPath: log4j2.yml
      volumes:
      - name: log4j2
        configMap:
          name: log4j2
