version: '3.7'
services:

  redis:
    image: redis:6.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    expose: [6379]

  routr-eet:
    image: fonoster/routr-eet:latest
    expose: [5061, 5062]
    env_file: env_test

  routr:
    links:
      - "routr-eet:sip.provider.net"
    build:
      context: .
    image: fonoster/routr:latest
    environment:
      EXTERN_ADDR: 127.0.0.1
      DATA_SOURCE_PROVIDER: redis_data_provider
      DATA_SOURCE_PARAMETERS: host=redis,port=6379
    expose: [4567, 5060]

  provisioner:
    image: fonoster/routr-ctl
    depends_on: 
      - routr-eet
    entrypoint: >
      /bin/sh -c "
        set -e;
        while ! nc -z routr 4567;do sleep 0.1; done
        rctl login https://routr:4567/api/v1beta1 -u admin -p changeit;
        rctl create -f /config/gateways.yml
        rctl create -f /config/numbers.yml
        rctl create -f /config/domains.yml
        rctl create -f /config/agents.yml
        while sleep 3600; do :; done
      "
    volumes:
      - ./config:/config:ro
