#!/usr/bin/env bash

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home

main_js="$(pwd)/mod/ctl/ctl.js"

for i in $(ls libs); do
    DEPS=$DEPS"libs/$i:";
done;

if [[ $(echo $JAVA_HOME 2>&1) != *"jdk-9"* ]];
then
    echo 'This app requires some  features from JS Nashorn (including ES6)';
    echo 'only available in Java 9. You MUST have Java 9!'
    echo 'Once installed just open the file ./sipioctl an replace JAVA_HOME with'
    echo 'the path to your JDK 9. We are working in making this easier...'
    exit;
fi

jjs -Dlog4j.configurationFile=config/log4j2.xml \
    -cp $DEPS --language=es6 -doe -ot -scripting=true "$main_js" -- "$@"
