#!/usr/bin/env sh
main_js="$(pwd)/etc/tests/test_helper.js"

echo "$@"

$GRAALVM_HOME/bin/js \
  --jvm \
  --experimental-options --js.nashorn-compat=true --js.scripting=true \
  --vm.cp=libs/app.deps.jar "$main_js" -- "$@"
