/**
 * Stores in memory information about sip transactions.
 *
 * @author Pedro Sanders
 * @since v1
 */
const TerminationCause = {
  '-1': 'UNKNOWN',
  '16': 'CAUSE_NORMAL_CLEARING',
  '1': 'CAUSE_UNALLOCATED',
  '17': 'CAUSE_USER_BUSY',
  '18': 'CAUSE_NO_USER_RESPONSE',
  '21': 'CAUSE_CALL_REJECTED',
  '28': 'CAUSE_INVALID_NUMBER_FORMAT',
  '34': 'CAUSE_NORMAL_CIRCUIT_CONGESTION',
  '200': 'CAUSE_NORMAL_CLEARING',
  '401': 'CAUSE_CALL_REJECTED',
  '403': 'CAUSE_CALL_REJECTED',
  '404': 'CAUSE_UNALLOCATED',
  '407': 'CAUSE_CALL_REJECTED',
  '408': 'CAUSE_NO_USER_RESPONSE',
  '420': 'CAUSE_NO_ROUTE_DESTINATION',
  '480': 'CAUSE_NO_ANSWER',
  '483': 'CAUSE_NO_ANSWER',
  '486': 'CAUSE_USER_BUSY',
  '487': 'CAUSE_NORMAL_CLEARING',
  '488': 'CAUSE_NOT_ACCEPTABLE_HERE',
  '503': 'CAUSE_SERVICE_UNAVAILABLE',
  '600': 'CAUSE_USER_BUSY',
  '604': 'CAUSE_UNALLOCATED',
  '603': 'CAUSE_CALL_REJECTED',
  '484': 'CAUSE_INVALID_NUMBER_FORMAT',
  '485': 'CAUSE_UNALLOCATED'
}

module.exports = terminationCode => {
  return TerminationCause[terminationCode] || 'UNKNOWN'
}
