#!/bin/bash

echo ""
echo "v1.0"
echo "____             _"
echo "|  _ \ ___  _   _| |_ _ __"
echo "| |_) / _ \| | | | __| '__|"
echo "|  _ < (_) | |_| | |_| |"
echo "|_| \_\___/ \__,_|\__|_|"
echo ""
echo "Next-generation SIP Server"
echo ""
