apiVersion: v1
entries:
  routr:
  - apiVersion: v2
    appVersion: 1.0.0-rc5
    created: "2023-08-14T14:32:07.486835476Z"
    dependencies:
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.18
    description: Next-generation SIP Server
    digest: 5e71e7a7f67234ea45d2470ccc536b7b723f45cd8c67b824995f2e76023f613a
    icon: https://routr.io/site_assets/images/avatar.png
    keywords:
    - routr
    - sip
    - voip
    - webrtc
    - ims
    - proxy
    - registrar
    - asterisk
    - kamailio
    - freepbx
    - yate
    - freeswitch
    - fusionpbx
    - server
    maintainers:
    - name: psanders
    name: routr
    sources:
    - https://github.com/fonoster/routr
    type: application
    urls:
    - routr-0.0.10.tgz
    version: 0.0.10
  - apiVersion: v2
    appVersion: 1.0.0-rc5
    created: "2023-08-14T14:32:07.495738582Z"
    dependencies:
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.18
    description: Next-generation SIP Server
    digest: 8d27a64017fbbb5fdc3d2960a99f78ba897f160aea0caac772e95829fb11ea05
    icon: https://routr.io/site_assets/images/avatar.png
    keywords:
    - routr
    - sip
    - voip
    - webrtc
    - ims
    - proxy
    - registrar
    - asterisk
    - kamailio
    - freepbx
    - yate
    - freeswitch
    - fusionpbx
    - server
    maintainers:
    - name: psanders
    name: routr
    sources:
    - https://github.com/fonoster/routr
    type: application
    urls:
    - routr-0.0.9.tgz
    version: 0.0.9
  - apiVersion: v2
    appVersion: 1.0.0-rc5
    created: "2023-08-14T14:32:07.490270455Z"
    dependencies:
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.6.18
    description: Next-generation SIP Server
    digest: a734ebb8c5fc13537de434f388e2757f179e8f4717eff6e9e815fcd429f72942
    icon: https://routr.io/site_assets/images/avatar.png
    keywords:
    - routr
    - sip
    - voip
    - webrtc
    - ims
    - proxy
    - registrar
    - asterisk
    - kamailio
    - freepbx
    - yate
    - freeswitch
    - fusionpbx
    - server
    maintainers:
    - name: psanders
    name: routr
    sources:
    - https://github.com/fonoster/routr
    type: application
    urls:
    - routr-0.0.8.tgz
    version: 0.0.8
  routr-connect:
  - apiVersion: v2
    appVersion: 2.1.8
    created: "2023-08-14T14:32:07.595121085Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: c6812da93d9804a7b4b10f3696c0493e0297bac9ad2e6ae7096c2761e68896f2
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 2.1.5
    created: "2023-08-14T14:32:07.582511893Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: 98f5d2da9789ef50ebb810aeac16cea2b28c42e81c697cf1b30eb5e044e80571
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 2.1.3
    created: "2023-08-14T14:32:07.570069205Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: cd6a8bcefca0218d8dc9a22ad630c30e183c62c055299ff117a39b19de824749
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 2.1.2
    created: "2023-08-14T14:32:07.556800597Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: 22da59bd3018b1258bb2dd389e39e44bc7668e751f397980da915b70365cefa2
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 2.0.28
    created: "2023-08-14T14:32:07.544647916Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: bdbd01c2e8182c820e0a4fca103fad146e9aa3e5d44c5e8b88164cc775215afd
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 2.0.24
    created: "2023-08-14T14:32:07.532411232Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: c25b94a6b94e537fe523854eee91a21813f024b34b1947f828429664890ba954
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 2.0.24
    created: "2023-08-14T14:32:07.520470655Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: 01e57fee551b65385bf72ce72ef3302186565d85e299d24dc1c08cd5e6b59a16
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 2.0.8-alpha.38
    created: "2023-08-14T14:32:07.508419576Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: b9d36b18b3323ab2afbc30eb53433c1e92068df9e83a52c3fdd3e169c3b688ca
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.1.tgz
    version: 0.1.1
generated: "2023-08-14T14:32:07.483042288Z"
