apiVersion: v1
entries:
  routr-connect:
  - apiVersion: v2
    appVersion: 2.0.28
    created: "2023-05-21T22:31:12.406844633Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.15
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.7.3
    description: Routr Connect Helm Chart
    digest: bdbd01c2e8182c820e0a4fca103fad146e9aa3e5d44c5e8b88164cc775215afd
    name: routr-connect
    type: application
    urls:
    - routr-connect-0.1.4.tgz
    version: 0.1.4
generated: "2023-05-21T22:31:12.390521804Z"
