/**
 * @author Pedro Sanders
 * @since v1
 */
export const RoutingType = {
    DOMAIN_INGRESS_ROUTING: 'DOMAIN_INGRESS_ROUTING',
    DOMAIN_EGRESS_ROUTING: 'DOMAIN_EGRESS_ROUTING',
    INTER_DOMAIN_ROUTING: 'INTER_DOMAIN_ROUTING',
    INTRA_DOMAIN_ROUTING: 'INTRA_DOMAIN_ROUTING',
    PEER_EGRESS_ROUTING: 'PEER_EGRESS_ROUTING'
}
