#!/usr/bin/env sh

set -e

BASE_DIR="$(cd "$(dirname "$0")"; pwd)"

[ -d "$BASE_DIR/usr/lib/jvm/java-8-openjdk-amd64" ] && JAVA_HOME=$BASE_DIR/usr/lib/jvm/java-8-openjdk-amd64

run() {
  cd $BASE_DIR
    $JAVA_HOME/bin/java \
    -Dlog4j.configurationFile=config/log4j2.yml \
    -Dpolyglot.js.experimental-foreign-object-prototype=true \
    -Dpolyglot.js.nashorn-compat=true \
    -Dnashorn.args="--no-deprecation-warning" \
    $ROUTR_JAVA_OPTS \
    -classpath "libs/*" \
    io.routr.core.Launcher
}

[ -z "$JAVA_HOME" ] && { echo "Could not find a runtime environment. Please setup environment variable JAVA_HOME"; exit 1; }

run
