name: publish to docker hub
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Download
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          BASE_URL=https://github.com/fonoster/routr/releases/download/$VERSION
          FILE=routr-${VERSION}_linux-x64_bin.tar.gz
          curl -L $BASE_URL/$FILE > $FILE
          tar xvf $FILE
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fonoster/routr
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          workdir: .
          tags: "latest, ${{ steps.get_version.outputs.VERSION }}"
