name: publish to gh pages
on:
  workflow_dispatch:
  push:
    paths:
    - 'docs/**'
    - '.charts/**'
    branches:
    - v1
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -Iv mkdocs==1.0.4
        pip install -Iv pymdown-extensions==6.0
        pip install -Iv mkdocs-material==4.4.0
    - name: Build
      run: |
        mkdocs build
        mkdir -p out/docs
        mv site/* out/docs
        mv docs/CNAME out
        mv docs/site_assets out
        mv docs/index.html out
        mv .charts out/charts
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./out
